### ISSUE TITLE
Plugin not being loaded with latest ckeditor

### ISSUE THREAD

**Issue by villagra** [pourquoi/ckeditor5-simple-upload#15]
Hi,
I'm having troubles installing the plugin with the latest ckeditor build, seems like the plugin is not being loaded.

I've created a simple repo ( a ckeditor5-build-classic fork):

https://github.com/villagra/ckeditor5-build-classic

Followed the instructions:

```
npm install 
npm install ckeditor5-simple-upload

modify ckeditor.js file
https://github.com/villagra/ckeditor5-build-classic/blob/master/src/ckeditor.js

add the plugin to the editor:
https://github.com/villagra/ckeditor5-build-classic/blob/master/sample/index.html#L31

```
But the plugin doesn't load. Any ideas?

**Comment by ims-one** [comment]
Same here.

![error](https://user-images.githubusercontent.com/24848472/58313161-3461a580-7e0d-11e9-9cdd-b14b03332bf7.png)

**Comment by ims-one** [comment]
@pourquoi, can you help?

**Comment by pourquoi** [comment]
Sorry for that, I fixed the documentation
you can see the fix here : https://github.com/pourquoi/ckeditor5-simple-upload/commit/8e850a1ad798a59c4e55814239cf488abb644be7

basically, activate the UploadAdapter and SimpleuploadPlugin

**Comment by ims-one** [comment]
Thank you so much. 
You are my hero today!
