### ISSUE TITLE
Not able to load toolbar insertImage

### ISSUE THREAD

**Issue by keatwei** [pourquoi/ckeditor5-simple-upload#3]
Not able to load toolbar insertImage

Build CKeditor5 classic 1.0.0-beta.1
<img width="546" alt="screen shot 2018-04-07 at 3 14 37 am" src="https://user-images.githubusercontent.com/6801014/38439937-1a8f96a2-3a12-11e8-8743-9885aaccf34e.png">

Not sure do I configure correctly or not

**Comment by khiconit** [comment]
Same problem

**Comment by pourquoi** [comment]
I've updated the plugin to latest beta 

run a npm update ckeditor5-simple-upload

and remove the 'insertImage' item from the toolbar, it's now named 'imageUpload' and it should already be there

**Comment by khiconit** [comment]
Thansk for your update
